"""
docx_service.py
---------------
Academic DOCX report generator for ResearchPilotAI.

Produces a properly structured DOCX document with:
  - Cover page with branding
  - Structured academic sections
  - Proper MIME type (application/vnd.openxmlformats-officedocument.wordprocessingml.document)
  - Footer: Generated by ResearchPilotAI / Developed by Nikhil Murugan
"""

import os
import logging
from datetime import datetime

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

from services.report_service import get_report_sections_preview, SECTION_ORDER
from services.ollama_service import OllamaError

logger = logging.getLogger(__name__)

DOCX_DIR = "reports"

# ── Colour palette ─────────────────────────────────────────────────────────────
PRIMARY_COLOR = RGBColor(16, 185, 129)    # #10B981 — matches UI accent
HEADING_COLOR = RGBColor(30, 41, 59)      # #1E293B — dark navy
MUTED_COLOR   = RGBColor(100, 116, 139)   # #64748B
WHITE         = RGBColor(255, 255, 255)
BODY_COLOR    = RGBColor(30, 41, 59)


# ── XML helpers ────────────────────────────────────────────────────────────────

def _add_page_number(run) -> None:
    """Insert a dynamic PAGE field into a run for Word page numbering."""
    fldChar1 = OxmlElement("w:fldChar")
    fldChar1.set(qn("w:fldCharType"), "begin")
    instrText = OxmlElement("w:instrText")
    instrText.set(qn("xml:space"), "preserve")
    instrText.text = "PAGE"
    fldChar2 = OxmlElement("w:fldChar")
    fldChar2.set(qn("w:fldCharType"), "separate")
    fldChar3 = OxmlElement("w:fldChar")
    fldChar3.set(qn("w:fldCharType"), "end")
    r = run._r
    r.append(fldChar1)
    r.append(instrText)
    r.append(fldChar2)
    r.append(fldChar3)


def _add_horizontal_rule(doc: Document) -> None:
    """Add a thin horizontal rule paragraph."""
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "10B981")
    pBdr.append(bottom)
    pPr.append(pBdr)
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(4)


def _set_cell_background(cell, hex_color: str) -> None:
    """Set table cell shading colour."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


# ── Main DOCX builder ──────────────────────────────────────────────────────────

def create_docx(content: str, output_filename: str | None = None) -> str:
    """
    Generate a structured academic DOCX report.

    Parameters
    ----------
    content         : Research topic or source material.
    output_filename : Optional custom filename (without path).

    Returns
    -------
    str — Absolute path to the saved .docx file.
    """
    if not content or not content.strip():
        raise OllamaError("Report content cannot be empty.")

    os.makedirs(DOCX_DIR, exist_ok=True)

    if not output_filename:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_filename = f"research_report_{timestamp}.docx"

    if not output_filename.lower().endswith(".docx"):
        output_filename += ".docx"

    output_path = os.path.join(DOCX_DIR, output_filename)

    logger.info("Generating DOCX report: %s", output_filename)

    # Generate content via report service (Ollama)
    sections = get_report_sections_preview(content)

    doc = Document()

    # ── Document metadata ──────────────────────────────────────────────────────
    core = doc.core_properties
    core.title = "Research Report"
    core.author = "Nikhil Murugan"
    core.company = "ResearchPilotAI"
    core.subject = "Academic Research Report"
    core.comments = "Generated by ResearchPilotAI — Developed by Nikhil Murugan"

    # ── Page margins: 1 inch all sides ────────────────────────────────────────
    for section in doc.sections:
        section.top_margin    = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin   = Inches(1.1)
        section.right_margin  = Inches(1.1)

    # ── Cover / title block ────────────────────────────────────────────────────
    # Brand bar via a 1-column table with coloured background
    cover_table = doc.add_table(rows=1, cols=1)
    cover_table.autofit = True
    cover_cell = cover_table.cell(0, 0)
    _set_cell_background(cover_cell, "10B981")

    cover_p = cover_cell.paragraphs[0]
    cover_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cover_p.paragraph_format.space_before = Pt(18)
    cover_p.paragraph_format.space_after  = Pt(18)
    cover_run = cover_p.add_run("ResearchPilotAI")
    cover_run.font.name  = "Calibri"
    cover_run.font.size  = Pt(13)
    cover_run.font.bold  = True
    cover_run.font.color.rgb = WHITE

    doc.add_paragraph()  # spacer

    # Report title
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_p.add_run("Research Report")
    title_run.font.name  = "Calibri"
    title_run.font.size  = Pt(28)
    title_run.font.bold  = True
    title_run.font.color.rgb = HEADING_COLOR

    # Metadata line
    date_str = datetime.now().strftime("%B %d, %Y")
    meta_p = doc.add_paragraph()
    meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta_p.add_run(f"Generated by ResearchPilotAI  ·  Nikhil Murugan  ·  {date_str}")
    meta_run.font.name   = "Calibri"
    meta_run.font.size   = Pt(10)
    meta_run.font.italic = True
    meta_run.font.color.rgb = MUTED_COLOR

    doc.add_paragraph()  # spacer

    _add_horizontal_rule(doc)

    # ── Sections ───────────────────────────────────────────────────────────────
    for heading in SECTION_ORDER:
        body_text = sections.get(heading, "Content not generated.").strip()

        # Section heading
        h_p = doc.add_paragraph()
        h_p.paragraph_format.space_before = Pt(20)
        h_p.paragraph_format.space_after  = Pt(4)
        h_run = h_p.add_run(heading.upper())
        h_run.font.name  = "Calibri"
        h_run.font.size  = Pt(13)
        h_run.font.bold  = True
        h_run.font.color.rgb = PRIMARY_COLOR

        _add_horizontal_rule(doc)

        # Body paragraphs (split on double newline)
        paragraphs = [p.strip() for p in body_text.split("\n\n") if p.strip()]
        if not paragraphs:
            paragraphs = [line.strip() for line in body_text.split("\n") if line.strip()]

        for para_text in paragraphs:
            p = doc.add_paragraph()
            p.paragraph_format.space_after  = Pt(8)
            p.paragraph_format.space_before = Pt(0)
            p.paragraph_format.line_spacing = Pt(14)
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            p_run = p.add_run(para_text)
            p_run.font.name  = "Calibri"
            p_run.font.size  = Pt(11)
            p_run.font.color.rgb = BODY_COLOR

    # ── Footer ─────────────────────────────────────────────────────────────────
    footer = doc.sections[0].footer
    # Remove any default paragraph
    for fp in footer.paragraphs:
        fp.clear()

    footer_table = footer.add_table(rows=1, cols=2, width=Inches(6.3))
    footer_table.autofit = True

    # Left: branding
    cell_left = footer_table.cell(0, 0)
    pl = cell_left.paragraphs[0]
    pl.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run_l = pl.add_run("Generated by ResearchPilotAI  ·  Developed by Nikhil Murugan")
    run_l.font.name  = "Calibri"
    run_l.font.size  = Pt(8)
    run_l.font.color.rgb = MUTED_COLOR

    # Right: page number
    cell_right = footer_table.cell(0, 1)
    pr = cell_right.paragraphs[0]
    pr.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run_prefix = pr.add_run("Page ")
    run_prefix.font.name  = "Calibri"
    run_prefix.font.size  = Pt(8)
    run_prefix.font.color.rgb = MUTED_COLOR

    run_page = pr.add_run()
    run_page.font.name  = "Calibri"
    run_page.font.size  = Pt(8)
    run_page.font.color.rgb = MUTED_COLOR
    _add_page_number(run_page)

    doc.save(output_path)
    logger.info("DOCX report saved: %s", output_path)
    return output_path
